server:
  port: 8080
  context-path: /

helloWorld: spring Boot\u5927\u7237\u4F60\u597D

msyql:
   jdbcName: com.mysql.jdbc.Driver
   dbUrl: jdbc:mysql://localhost:3306/wj
   userName: root
   password: 123

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wj?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
     database-platform: com.lunwen.wangjie.config.MySQL5DialectUTF8

   thymeleaf:
     cache: false